[package]
name = "dm-checks"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dm-scan = { path = "../dm-scan" }
dm-meta = { path = "../dm-meta" }
chrono.workspace = true
thiserror.workspace = true
